"""
Agent notes board.

Lightweight in-memory store for free-form investigation notes that agents can
publish during a pipeline run, with comment threads that any agent (or the
human user) can reply on. Visible from the dashboard's Notes page so the team
can review the conversation between agents post-run, similar to a Confluence
page with inline comments — but auto-generated by the agents themselves.

Wired in two ways:
  1. Agents that broadcast a special "note" via the AgentBus get auto-promoted
     into a Note here (see hook in bus.py).
  2. The /api/notes/* REST endpoints let the dashboard read and add comments.
"""
from __future__ import annotations

import time
import uuid
from dataclasses import asdict, dataclass, field
from typing import Any


@dataclass
class NoteComment:
    id: str
    author: str          # agent_id or "user"
    body: str
    created_at: float


@dataclass
class Note:
    id: str
    author: str          # agent_id
    title: str
    body: str
    tags: list[str] = field(default_factory=list)
    ticket_key: str = ""
    pipeline_run_id: str = ""
    created_at: float = field(default_factory=time.time)
    comments: list[NoteComment] = field(default_factory=list)


# In-memory store. For demo purposes only — swap for SQLite + a notes table
# in production.
_notes: list[Note] = []


def list_notes(ticket_key: str | None = None) -> list[dict[str, Any]]:
    """Return all notes (optionally filtered by ticket key), newest first."""
    items = list(_notes)
    if ticket_key:
        items = [n for n in items if n.ticket_key == ticket_key]
    items.sort(key=lambda n: n.created_at, reverse=True)
    return [asdict(n) for n in items]


def get_note(note_id: str) -> dict[str, Any] | None:
    for n in _notes:
        if n.id == note_id:
            return asdict(n)
    return None


def add_note(
    *, author: str, title: str, body: str,
    tags: list[str] | None = None,
    ticket_key: str = "",
    pipeline_run_id: str = "",
) -> dict[str, Any]:
    note = Note(
        id=str(uuid.uuid4())[:8],
        author=author or "system",
        title=(title or "").strip()[:200] or "(untitled)",
        body=(body or "").strip(),
        tags=tags or [],
        ticket_key=ticket_key,
        pipeline_run_id=pipeline_run_id,
    )
    _notes.append(note)
    # Cap to 200 notes so the in-memory list doesn't grow forever
    if len(_notes) > 200:
        del _notes[0 : len(_notes) - 200]
    return asdict(note)


def add_comment(note_id: str, *, author: str, body: str) -> dict[str, Any] | None:
    for n in _notes:
        if n.id == note_id:
            comment = NoteComment(
                id=str(uuid.uuid4())[:8],
                author=author or "user",
                body=(body or "").strip(),
                created_at=time.time(),
            )
            n.comments.append(comment)
            return asdict(comment)
    return None


def delete_note(note_id: str) -> bool:
    global _notes
    before = len(_notes)
    _notes = [n for n in _notes if n.id != note_id]
    return len(_notes) != before


def clear_all() -> None:
    """Clear every note (used for tests/demos)."""
    _notes.clear()
